project:
  type: website
  output-dir: docs

book:
  title: "R-Cookbook"
  author: "Bradford Johnson"
  date: "8/27/2022"
  chapters:
    - index.qmd
    - collecting-data.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Preface"
        file: index.qmd
      - collecting-data.qmd
      